name: build

on:
  - push
  - pull_request

jobs:

  macos:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin
      - name: Install deps
        run: |
          brew update
          brew install automake autoconf libtool pkg-config coreutils gnu-sed wget meson ninja

      - name: Download deps
        run: |
          cd buildscripts && TRAVIS=1 ./download.sh

      - name: Download mpv
        run: |
          cd buildscripts && mkdir deps/mpv
          wget https://github.com/mpv-player/mpv/archive/master.tar.gz -O master.tgz
          tar -xzf master.tgz -C deps/mpv --strip-components=1 && rm master.tgz

      - name: Build
        run: |
          cd buildscripts && ./buildall.sh
